---
title: Digital@DAI
timezone: UTC
collections:
  authors:
    title: Authors
    output: true
    permalink: "/authors/:path/"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    Author: 
    layout: post
- scope:
    path: ''
    type: authors
  values:
    layout: author
    Job: 
    Image: 
url: http://dai-global-digital.com
gems:
- jekyll-paginate
paginate: 3
paginate_path: "/page:num/"
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
excerpt_separator: "<!--more-->"
email: your-email@domain.com
exclude:
- ".gitignore"
description: The Digital for Development field has enormous potential—and plenty of
  room for learning. We launched this blog as part of our own learning process, and
  we hope to engage the Digital for Development community as we find our way forward
baseurl: 
destination: "./build"
sass:
  style: compressed
