---
title: Digital@DAI
url: http://dai-global-digital.com
timezone: UTC
collections:
  uploads:
    title: Uploads
    output: true
  authors:
    title: Authors
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    Author:
    layout: project
- scope:
    path: ''
    type: authors
  values:
    layout: page
gems:
- jekyll-paginate
paginate: 3
paginate_path: "/page:num/"
hilighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
excerpt_separator: "<!--more-->"
email: your-email@domain.com
exclude:
- ".gitignore"
description: |
  Write an awesome description for your new site here.
baseurl:
destination: "./build"
sass:
  style: compressed
